#!/bin/sh
# Copyright (C) 2007-2013, GoodData(R) Corporation. All rights reserved
#
# GoodData Smoke testing daemon
#
# chkconfig:   - 70 30
#
# description: GoodData Smoke testing daemon

# Source function library.
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions

# Source LSB function library.
. /lib/lsb/init-functions

PROG='smokerd'
BINARY='/usr/bin/smokerd.py'
PIDFILE='/var/run/smokerd.pid'
LOCKFILE='/var/lock/subsys/smokerd'
CONFDIR='/etc/smokerd'
CONFIG="${CONFDIR}/smokerd.yaml"
SMOKERD_OPTIONS="-p ${PIDFILE} -v -c ${CONFIG}"

# Overwrite options
[ -f /etc/default/smokerd ] && . /etc/default/smokerd

start() {
	start_daemon -p $PIDFILE $BINARY $SMOKERD_OPTIONS
}

stop() {
	# This is left intentionally for transition - we don't want to keep the
	# old lockfile in place
	rm -f $LOCKFILE

	killproc -p $PIDFILE -d 120 $BINARY
}

rhstatus() {
	status -p "$PIDFILE" -l $PROG $BINARY
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	restart
	;;
  reload)
	exit 3
	;;
  force-reload)
	restart
	;;
  status)
	rhstatus
	;;
  condrestart|try-restart)
	rhstatus >/dev/null 2>&1 || exit 0
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status}"
	exit 3
esac

exit $?
